# Generated by Django 5.0.6 on 2024-09-05 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='user',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mentor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
